INSERT INTO REGISTRO( CAMPO1,CAMPO2) VALUES (12,'TESTE 1');
INSERT INTO REGISTRO( CAMPO1,CAMPO2) VALUES (87,'TESTE 2');
--INSERT INTO REGISTRO( CAMPO1,CAMPO2) VALUES (12,'TESTE');
--INSERT INTO REGISTRO( CAMPO1,CAMPO2) VALUES (12,'TESTE');
--INSERT INTO REGISTRO( CAMPO1,CAMPO2) VALUES (12,'TESTE');
--INSERT INTO REGISTRO( CAMPO1,CAMPO2) VALUES (12,'TESTE');
--INSERT INTO REGISTRO( CAMPO1,CAMPO2) VALUES (12,'TESTE');
--INSERT INTO REGISTRO( CAMPO1,CAMPO2) VALUES (12,'TESTE');
--INSERT INTO REGISTRO( CAMPO1,CAMPO2) VALUES (12,'TESTE');
--INSERT INTO REGISTRO( CAMPO1,CAMPO2) VALUES (12,'TESTE');
--INSERT INTO REGISTRO( CAMPO1,CAMPO2) VALUES (12,'TESTE');
--INSERT INTO REGISTRO( CAMPO1,CAMPO2) VALUES (12,'TESTE');
--INSERT INTO REGISTRO( CAMPO1,CAMPO2) VALUES (12,'TESTE');
--INSERT INTO REGISTRO( CAMPO1,CAMPO2) VALUES (12,'TESTE');
--INSERT INTO REGISTRO( CAMPO1,CAMPO2) VALUES (12,'TESTE');
--INSERT INTO REGISTRO( CAMPO1,CAMPO2) VALUES (12,'TESTE');

